### ISSUE TITLE
Compare with Cython implement

### ISSUE THREAD

**Issue by v-nhandt21** [Maghoumi/pytorch-softdtw-cuda#12]
Thank you @Maghoumi  , I am investigating your amazing source code, but have you compare this with the Cython implement: https://github.com/mblondel/soft-dtw 

I have used your softDTW in CUDA but with the Batch Size = 1, my GPU is nearly Out of memory, can not increase more

![image](https://user-images.githubusercontent.com/36092323/134486922-0a613022-4e99-49fc-bef4-5aa46c2e57ab.png)

Here is my input size, 

![image](https://user-images.githubusercontent.com/36092323/134487297-b8dee43e-9da7-4746-8ab2-37dfa7f50717.png)

I wonder how can you use the batch size up to 256

**Comment by Maghoumi** [comment]
Sorry for the late response.

> but have you compare this with the Cython implement: https://github.com/mblondel/soft-dtw

Compare in what sense? In terms of speed, there's already a [profiling function](https://github.com/Maghoumi/pytorch-softdtw-cuda/blob/master/soft_dtw_cuda.py#L382) that compares the speed.

> I wonder how can you use the batch size up to 256

It's a generic question, and the answer of course depends on what hardware you're using and what the nature of your data is. In our case, our data consisted of sequences with the length of at most 64 steps and overall fairly small. Also, our experiments were running with GPUs that had 32GB of VRAM.

**Comment by v-nhandt21** [comment]
> Sorry for the late response.
> 
> > but have you compare this with the Cython implement: https://github.com/mblondel/soft-dtw
> 
> Compare in what sense? In terms of speed, there's already a [profiling function](https://github.com/Maghoumi/pytorch-softdtw-cuda/blob/master/soft_dtw_cuda.py#L382) that compares the speed.
> 
> > I wonder how can you use the batch size up to 256
> 
> It's a generic question, and the answer of course depends on what hardware you're using and what the nature of your data is. In our case, our data consisted of sequences with the length of at most 64 steps and overall fairly small. Also, our experiments were running with GPUs that had 32GB of VRAM.

Thank you, I found that my feature up to [sequence len = 1024, hidden dim=80], it seems too long for softDTW to run with large batch size, my GPU is RTX3090.
