### ISSUE TITLE
GPU mem still be affected when using CPU Soft DTW 

### ISSUE THREAD

**Issue by v-nhandt21** [Maghoumi/pytorch-softdtw-cuda#13]
Here is my testing with dim_feature = 80

![image](https://user-images.githubusercontent.com/36092323/134720978-7d4ded5e-9933-4e99-aea3-d63c4e0484af.png)

The space complexity seems to be O(Frame time^2)

I just wonder why GPU mem still be affected when using CPU Soft DTW implementation

**Comment by Maghoumi** [comment]
Can you post a minimally working example?

**Comment by v-nhandt21** [comment]
> 

Sorry for my late reply, I just wonder that Soft DTW can run with cpu if the sequence length > 1024, so why it still get Cuda out of memory in GPU :))
