### ISSUE TITLE
Steps chosen / choice penalty

### ISSUE THREAD

**Issue by cfrancesco** [Maghoumi/pytorch-softdtw-cuda#2]
Hi,
thanks for the implementation!
I'm still unfamiliar with it, would it be possible to extract or store the steps (or choice) taken during the optimization as it is doable with normal dwt implementations?
Or, equivalently, adding penalty terms for the different choices?

**Comment by Maghoumi** [comment]
Hi @cfrancesco 
Thanks for your interest in my code.

With sDTW, I don't think it's possible to get the "best path" using the cost matrix. The reason for that is the sDTW algorithm actually returns a value that corresponds to all possible alignment between the two inputs, weighted by their probability (see the comment from the original authors here: https://github.com/mblondel/soft-dtw/issues/10#issuecomment-383377409).

This question is probably best posted in the original sDTW repo.

**Comment by cfrancesco** [comment]
Ok, thank you! Then I'll investigate how to add penalties rather than inspecting the optimal path.
I'll post any update, should there be any.

**Comment by Maghoumi** [comment]
No problem! Sure please do.
Also, please consider starring this repository if you find it helpful :)
