### ISSUE TITLE
[Feature request] Add backtracking/compatibility with other tools

### ISSUE THREAD

**Issue by janvainer** [Maghoumi/pytorch-softdtw-cuda#6]
There seems to be no out of the box backtracking option to extract. 
Are the results expected to be compatible with non-differentiabe dtw toolkits such as [dtw](https://dynamictimewarping.github.io/py-api/html/api/dtw.dtw.html) that provide the backtracking functionality? I tried using [dtw-python](https://dynamictimewarping.github.io/python/) for alignment extraction and it seems to work pretty well. :)

**Comment by Maghoumi** [comment]
Hi @janvainer, this is similar to the discussion in #2. Please refer to that issue.
